### ISSUE TITLE
ESP32-S3

### ISSUE THREAD

**Issue by StuartIanNaylor** [42io/esp32_kws#2]
Just wondering if you know or are able to optimise for esp32?
The FFT routines on the S3 are just shy of x10 perf of the normal esp32 due to vector math.
https://docs.espressif.com/projects/esp-dsp/en/latest/esp-dsp-benchmarks.html
Supposedly ML is 4-6x but still trying to work out if tflite-micro has been optimised.
Also xtensa do a LSTM layer which is very interesting for streaming models but again confused if implemented for S3

Just thought I would ask if you knew any more with the S3 being so new.

**Comment by mazko** [comment]
S3 is new chip, i don't have one. From what i see https://docs.espressif.com/projects/esp-dsp/en/latest/esp-dsp-benchmarks.html i expected much more. Maybe functions dspm_mult_f32, FFTs 16 bit Fixed Point are interesting...

I played a little with esp-dsp https://github.com/espressif/esp-dsp/issues/22 before, there was no significant improvement comparing to kissfft compiled with optimization -O3.  Same for dot product. esp-dsp is just asm implementotion, there is no dsp actually :)

See https://github.com/42io/dataset/blob/01112d34795c04754209cd480488dec9256e7225/google_speech_commands/src/features/fast/magspec.c for fft functions you can replace by your implemenation.

**Comment by StuartIanNaylor** [comment]
Yeah think its only vector instructions but still trying to work out which and what and also what compilers.
FFTs 16 bit Fixed Point seems to get a big boost and guess the vector instructions are fixed point
